spring:
  application:
    name: analysis-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:antiplagiarism}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

server:
  port: 8082

file:
  service:
    url: ${FILE_SERVICE_URL:http://file-storing-service:8081}

logging:
  level:
    com.antiplagiarism: INFO